name: conlamduoc
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^0.3.20
  flutter_launcher_icons: ^0.7.4
  intl: ^0.16.0
  nuts_activity_indicator: ^0.1.1
  flutter_datetime_picker: ^1.3.8
  reflectable: any
  path_provider: ^1.6.7
  image_picker: ^0.6.5+2

  image_cropper: ^1.0.2
  video_player: ^0.10.9+1
  chewie: ^0.9.10

  tiengviet: ^0.3.0

  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_square.png"
  adaptive_icon_background: "assets/logo/background.png"
#  adaptive_icon_foreground: "assets/usrunlogo/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/data/userList.json
    - assets/data/lessons/lessonList.json
    - assets/data/feeds/feedList.json
    - assets/data/challenge/challengeList.json
    - assets/data/quizzes/quizList.json
    - assets/localization/en.json

    - assets/logo/logo.png
    - assets/logo/logo_square.png
    - assets/logo/background.png

    - assets/icons/home.png
    - assets/icons/lesson.png
    - assets/icons/game.png
    - assets/icons/challenge.png
    - assets/icons/profile.png
    - assets/icons/search.png
    - assets/icons/close_whitebold.png
    - assets/icons/coin.png

    - assets/icons/calendar.png
    - assets/icons/icon_avatar.png
    - assets/icons/add_friend.png
    - assets/icons/close_whitebold.png

    - assets/images/title_profile.png
    - assets/images/welcome_background.png
    - assets/images/button_challenge.png
    - assets/images/button_join.png
    - assets/images/button_like_color.png
    - assets/images/button_like_nocolor.png
    - assets/images/button_login.png
    - assets/images/button_quiz.png
    - assets/images/button_joinclass.png
    - assets/images/whale_image.png
    - assets/images/default_image.png
    - assets/images/LichSu_image.jpg
    - assets/images/LePhep_image.png
    - assets/images/pencil_image.jpg
    - assets/icons/check_whitebold.png

    - assets/images/title_challenge.png
    - assets/images/title_home.png
    - assets/images/title_lesson.png
    - assets/images/title_game.png
    - assets/images/title_hello.png
    - assets/images/title_profile.png

    - assets/images/avatar.png
    - assets/images/challenge1.png
    - assets/images/challenge2.png
    
    - assets/images/game_background.png
    - assets/images/game_name.png
    - assets/images/game_line.png
    - assets/images/game_process.png
    - assets/images/button_play.png
    - assets/images/button_howtoplay.png
    - assets/images/game_incorrect.png
    - assets/images/game_correct.png
    - assets/images/layout_game4.png